from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class LatencyMetrics(BaseModel):
    """Structured breakdown of execution latency across pipeline stages."""

    stt_ms: float = Field(default=0.0, description="Sarvam STT latency in milliseconds")
    query_processing_ms: float = Field(default=0.0, description="Query processing latency in milliseconds")
    embedding_ms: float = Field(default=0.0, description="Vector embedding latency in milliseconds")
    retrieval_ms: float = Field(default=0.0, description="Qdrant retrieval latency in milliseconds")
    reranking_ms: float = Field(default=0.0, description="Reranking latency in milliseconds")
    context_building_ms: float = Field(default=0.0, description="Context assembly latency in milliseconds")
    generation_ms: float = Field(default=0.0, description="LLM answer generation latency in milliseconds")
    guardrails_ms: float = Field(default=0.0, description="Guardrails verification latency in milliseconds")
    total_ms: float = Field(default=0.0, description="Total wall-clock latency in milliseconds")


class SourceChunk(BaseModel):
    """Schema for retrieved document passage citation source."""

    chunk_id: str = Field(..., description="Unique chunk identifier")
    doc_id: str = Field(..., description="Source document identifier")
    score: float = Field(..., description="Relevance or similarity score")
    text: str = Field(..., description="Passage text content")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata key-value pairs (language, title, etc.)")


class HealthResponse(BaseModel):
    """Schema for GET /health endpoint response."""

    status: str = Field(default="ok", description="Global backend health status")
    service: str = Field(default="voice-rag-backend", description="Service identifier name")
    version: str = Field(default="0.1.0", description="Service version")
    qdrant_connected: bool = Field(default=False, description="Vector DB reachability status")
    environment: str = Field(default="development", description="Execution environment")


class RAGResponse(BaseModel):
    """Schema for RAG query answer response."""

    request_id: str = Field(..., description="Unique request tracking identifier")
    query: str = Field(..., description="Original or transcribed user query")
    transcription: Optional[str] = Field(default=None, description="STT transcript text if input was voice")
    answer: str = Field(..., description="Grounded answer generated by LLM")
    sources: List[SourceChunk] = Field(default_factory=list, description="Retrieved source document passages")
    latency: LatencyMetrics = Field(..., description="Latency telemetry breakdown")
    guardrail_passed: bool = Field(default=True, description="Whether output passed guardrail verification")


class ErrorDetails(BaseModel):
    """Structured error payload details."""

    code: str = Field(..., description="Error classification code")
    message: str = Field(..., description="Human-readable error description")
    request_id: str = Field(..., description="Request tracking identifier")
    details: Dict[str, Any] = Field(default_factory=dict, description="Additional context or diagnostics")


class ErrorResponse(BaseModel):
    """Schema for standardized API error responses."""

    error: ErrorDetails = Field(..., description="Error container object")
